-------
Select
       signups.id as signup_id,
       signups.why_participated,
       signups.source as signup_source,
       signups.details as signup_details,
       signups.source_bucket as signup_source_bucket,
       signups.created_at as signup_created_at,
       signups.source_details,
       signups.utm_medium as signup_utm_medium,
       signups.utm_source as signup_utm_source,
       signups.utm_campaign as signup_utm_campaign,
       signups.signup_rank,
       posts.action as post_action,
       posts.action_id as post_action_id,
       posts.created_at as post_created_at,
       posts.id as post_id,
       posts.is_accepted as post_is_accepted,
       posts.is_anonymous as post_is_anonymous,
       posts.is_civic_action as post_is_civic_action,
       posts.is_online as post_is_online,
       posts.is_quiz as post_is_quiz,
       posts.is_reportback,
       posts.is_scholarship_entry as post_is_scholarship_entry,
       posts.time_commitment as post_is_commitment,
       posts.is_volunteer_credit,
       posts.location as post_location,
       posts.northstar_id as post_northstar_id,
       posts.noun as post_noun,
       posts.num_participants,
       posts.postal_code as post_postal_code,
       posts.post_class,
       posts.quantity as post_quantity,
       CASE
        WHEN  posts.quantity   > 10000 THEN 1
        WHEN  posts.quantity   IS NULL THEN 1
             ELSE  posts.quantity   END AS post_quantity_clean,
       posts.referrer_user_id as post_referrer_user_id,
       posts.reportback_volume as post_reportback_volume,
       posts.school_id as post_school_id,
       posts.source_bucket as post_source_bucket,
       posts.signup_id as post_signup_id,
       posts.source as post_source,
       posts.status as post_status,
       posts.text as post_text,
       posts.type as post_type,
       posts.hours_spent as post_hours_spent,
       posts.url as post_url,
       posts.verb as post_verb,
       posts.vr_source as post_vr_source,
       posts.vr_source_details as post_vr_source_details,
       posts.tags as post_tags,
       reportbacks.post_action as reportback_action,
       reportbacks.location as reportback_location,
       reportbacks.reportback_volume,
       reportbacks.tags as reportback_tags,
       campaign_info.campaign_id,
       campaign_info.campaign_run_id,
       campaign_info.campaign_name,
       campaign_info.campaign_cause,
       campaign_info.campaign_run_start_date,
       campaign_info.campaign_run_end_date,
       campaign_info.campaign_created_date,
       campaign_info.campaign_node_id,
       campaign_info.group_type_id,
       campaign_info.contentful_id,
       campaign_info.contentful_internal_title,
       campaign_info.contentful_title,
       campaign_info.contentful_raf_flag,
       campaign_info.campaign_node_id_title,
       campaign_info.campaign_run_id_title,
       campaign_info.campaign_action_type,
       campaign_info.campaign_cause_type,
       campaign_info.campaign_cta,
       campaign_info.action_types,
       campaign_info.online_offline,
       campaign_info.scholarship,
       campaign_info.post_types,
       users.northstar_id,
       users.created_at user_created_at,
       users.club_id,
       users.last_logged_in,
       users.last_accessed,
       users.last_messaged_at,
       users.drupal_uid,
       users.source as user_source,
       users.email,
       users.email_subscription_topics,
       users.facebook_id,
       users.mobile,
       users.birthdate,
       users.voter_registration_status,
       users.city as user_city,
       users.state as User_state,
       users.zipcode as user_zipcode,
       users.country as user_country,
       users.language as user_language,
       users.cio_status,
       users.cio_status_timestamp,
       users.sms_status,
       users.source_detail,
       users.utm_medium as user_utm_medium,
       users.utm_source as user_utm_source,
       users.utm_campaign as user_utm_campaign,
       users.contentful_id as user_contentful_id,
       users.legacy_badges_flag,
       users.badges,
       users.total_badges,
       users.refer_friends,
       users.refer_friends_scholarship,
       users.subscribed_member,
       users.last_updated_at,
       users.school_id as user_school_id,
       users.causes,
       users.referrer_user_id
from signups
         left outer join posts on signups.id = posts.signup_id
         left outer join reportbacks on posts.id = reportbacks.post_id
         left outer join campaign_info on signups.campaign_id = cast(campaign_info.campaign_id as varchar)
         left outer join users on users.northstar_id = signups.northstar_id
where campaign_info.campaign_id >= '9100'