SELECT action_id,
       browser_size,
       clicked_link_url,
       device_id,
       event_datetime,
       event_id,
       event_name,
       event_source,
       event_type,
       host,
       northstar_id,
       referrer_host,
       referrer_path,
       referrer_source,
       se_action,
       se_category,
       se_label,
       session_counter,
       session_id,
       block_id,
       campaign_id,
       campaign_name,
       context_source,
       context_value,
       group_id,
       modal_type,
       path,
       page_id,
       search_query,
       utm_campaign,
       utm_medium,
       utm_source,
       query_parameters
--        , COUNT(DISTINCT (phoenix_next_events."event_id")) AS "phoenix_next_events.count"
FROM quasar_prod_warehouse.public.snowplow_raw_events AS phoenix_next_events
WHERE phoenix_next_events.event_name = 'phoenix_clicked_download_button_volunteer_credits_table'
and action_id = '1160'
-- group by phoenix_next_events.action_id